- hosts: jenkins
  connection: local
  hosts: localhost
  become: true
  tasks:
  - name: jenkins user
    user:
      name: jenkins
      shell: /bin/bash

  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
      update_cache: true 

  - name: jenkins gpg key
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present

  - name: jenkins apt repo
    apt_repository:
      repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      state: present

  - name: jenkins install
    apt:
      name: jenkins
      state: latest
      update_cache: true

  - name: jenkins service
    service:
      name: jenkins
      state: started
